[package]
name = "stable_structures"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.8.1"
ic-cdk = "0.6.0"
ic-cdk-macros = "0.6.0"
ic-stable-structures = "0.5.0"
serde = "1.0.136"

[[bin]]
name = "stable_structures"
path = "src/main.rs"

