[package]
name = "certificate_orchestrator"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "certificate_orchestrator"
path = "src/main.rs"

[dependencies.certificate_orchestrator_interface]
path = "../certificate_orchestrator_interface"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.58"
bincode = "1.3.3"
candid = "0.8.4"
cfg-if = "1.0.0"
hex = "0.4.3"
ic-cdk = "0.7.0"
ic-cdk-timers = "0.1.0"
ic-cdk-macros = "0.6.8"
ic-certified-map = "0.3.2"
ic-stable-structures = "0.2.0"
priority-queue = { version = "1.3.0", features = ["serde"] }
prometheus = "0.13.3"
serde = "1.0.147"
serde_bytes = "0.11.7"
sha2 = "0.10.6"
thiserror = "1.0.37"
mockall = "0.11.3"
