[package]
name = "ic-crypto-utils-time"
version = "0.8.0"
edition = "2021"
description = "Utils for time source"

[dependencies]
ic-logger = { path = "../../../monitoring/logger" }
ic-interfaces = { path = "../../../interfaces" }
ic-types = { path = "../../../types/types" }
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
