[package]
name = "ic-crypto-test-utils-local-csp-vault"
version = "0.8.0"
edition = "2021"
description = "Test utilities for local CSP vault"

[dependencies]
ic-crypto-internal-csp = { path = "../../internal/crypto_service_provider"}
ic-crypto-internal-seed = { path = "../../internal/crypto_lib/seed" }
ic-crypto-internal-threshold-sig-bls12381 = { path = "../../internal/crypto_lib/threshold_sig/bls12_381" }
ic-crypto-internal-threshold-sig-ecdsa = { path = "../../internal/crypto_lib/threshold_sig/tecdsa" }
ic-crypto-internal-types = { path = "../../internal/crypto_lib/types" }
ic-crypto-node-key-validation = {path = "../../node_key_validation" }
ic-crypto-tls-interfaces = { path = "../../tls_interfaces" }
ic-types = { path = "../../../types/types" }
mockall = "0.7.2"
