[package]
name = "ic-p2p-exp-prototype"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-artifact-manager = { path = "../../../artifact_manager" }
ic-interfaces = { path = "../../../interfaces" }
ic-types = { path = "../../../types/types" }
tokio = { version = "1.15.0", features = ["full"] }
