[package]
name = "ic-crypto-for-verification-only"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-interfaces = { path = "../../interfaces" }
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-crypto-temp-crypto = { path = "../temp_crypto" }
ic-crypto-tls-interfaces = { path = "../tls_interfaces" }

[dev-dependencies]
ic-crypto-test-utils = { path = "../test_utils" }
ic-registry-client-fake = { path = "../../registry/fake" }
ic-registry-proto-data-provider = { path = "../../registry/proto_data_provider" }
ic-types = { path = "../../types/types" }
