[package]
name = "ic-icrc1-benchmark-generator"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ic-icrc1-benchmark-generator"
path = "src/main.rs"

[dependencies]
async-trait = "0.1.53"
candid = "0.8.1"
ciborium = "0.2"
dfn_http_metrics = {path = "../../../../rust_canisters/dfn_http_metrics"}
futures = "0.3.25"
# !!!! IMPORTANT FOR CANISTERS !!!
getrandom = { version = "0.2", features = ["custom"] }
hex = "0.4.2"
ic-base-types = { path = "../../../../types/base_types" }
ic-crypto-tree-hash = { path = "../../../../crypto/tree_hash" }
ic-cdk = { version = "0.6.0" }
ic-cdk-macros = { version = "0.6.0" }
ic-icrc1 = { path = "../.." }
ic-icrc1-benchmark-worker = { path = "../worker"}
ic-icrc1-client = { path = "../../client"}
ic-icrc1-client-cdk = { path = "../../client/cdk" }
ic-ledger-canister-core = { path = "../../../ledger_canister_core" }
ic-ledger-core = { path = "../../../ledger_core" }
ic-metrics-encoder = "1"
num-traits = "0.2.14"
rand = { version = "0.8.5", features = ["small_rng"]}
rand_core = "0.6.4"
rand_chacha = "0.3.1"
ring = { version = "0.16.11", features = ["std"] }
serde = "1.0"
serde_bytes = "0.11"
