[package]
name = "config_writer_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.0"
service-discovery = { path = "../service_discovery" }
ic-types = { path = "../../types/types" }
slog = { version = "2.5.2", features = ["nested-values"] }
slog-async = { version = "2.5", features = ["nested-values"] }
slog-term = "2.6.0"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.54"
ic-utils = { path = "../../utils/" }
erased-serde = "0.3.23"
serde_derive = "1.0.150"
crossbeam = "0.8.0"
crossbeam-channel = "0.5.5"
