[package]
name = "ic-crypto-ecdsa-secp256k1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
k256 = { version = "0.11.6", features = ["ecdsa", "pkcs8"] }
pem = "1.1.0"
zeroize = { version = "1.5", features = ["zeroize_derive"] }
simple_asn1 = "0.6.1"
rand = "0.8"
lazy_static = "1.4"

[dev-dependencies]
hex = "0.4"
wycheproof = "0.4"
