[package]
name = "ic-test-utilities-in-memory-logger"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-config = { path = "../../config" }
ic-logger = { path = "../../monitoring/logger" }
ic-protobuf = { path = "../../protobuf" }
serde_json = "1.0.89"
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
slog-async = { version = "2.5", features = ["nested-values"] }
parking_lot = "0.12.1"
