[package]
name = "ic-crypto-test-utils-metrics"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-crypto-internal-logmon = { path = "../../internal/logmon" }
ic-metrics = { path = "../../../monitoring/metrics" }
prometheus = { version = "0.12.0", features = [ "process" ] }
strum = "0.23.0"
strum_macros = "0.23.0"
